server:
  port: 8090
spring:
  # mysql配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ho_pass?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 30000
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    database: 0
  # activeMQ配置
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    close-timeout: 15s
    in-memory: true
    non-blocking-redelivery: false
    send-timeout: 0
    queue-name: active.queue
    topic-name: active.topic.name.model
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 30000
    packages:
      trust-all: true
  data:
    mongodb:
      uri: mongodb+srv://hokoory:HEjiale5201314@cluster0.fyrww.azure.mongodb.net/ho?retryWrites=true&w=majority
# Mybatis 配置
mybatis:
  mapper-locations: classpath:/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
