server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ho_pass?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
